---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
**1.unzip and loading data**

**2.making data$date to format class Date**

```{r}
# unzip and loading data
unzip("activity.zip")
data<-read.csv("activity.csv")
#for seeing
head(data)
#and it's structure
str(data)


#preprocessing data

 
data$date<-as.Date(data$date)

#finally it's structure
str(data)
```
## What is mean total number of steps taken per day?

```{r}
total_steps<-aggregate(steps~date,data,sum)
#seeing mean_steps
print(total_steps)
#histogram
hist(total_steps$steps,col="green",xlab="steps",main="total steps by day")
#it's mean
mean(total_steps$steps,na.rm=T)
#or median
median(total_steps$steps,na.rm=T)
```

## What is the average daily activity pattern?


```{r}
mean_steps<-aggregate(steps~interval,data,mean)
#seeing head
head(mean_steps)
#seeing tail
tail(mean_steps)
#ploting
plot(mean_steps$steps~mean_steps$interval,type="l",col="green",xlab="interval",ylab="steps",main="mean steps by day")

#2. Which 5-minute interval, on average across all the days in the #dataset, contains the maximum number
#of steps?
n_steps_max <- which.max(mean_steps$steps)
interval_of_max <- mean_steps$interval[n_steps_max]
interval_of_max
```

## Imputing missing values
```{r}
#1. Calculate and report the total number of missing values in the #dataset (i.e. the total number of rows with
#NA s)
sum(!complete.cases(data))

```
## Are there differences in activity patterns between weekdays and  ?
```{r}

days <- weekdays(data$date)
data$day_type <- ifelse(days == "Samedi" | days == "Dimanche", 
                                "Weekend", "Weekday")
data$day_type<-as.factor(data$day_type)
week_data<-aggregate(interval~steps + day_type,data,mean)
head(week_data)

```